CAPABILITIES = [
    {
        "capability_id":"glip.project_summary",
        "version":"1.0.0",
        "description":"Summarize authorized project state without external writes.",
        "input_schema":"glip.project-summary.request.v1",
        "output_schema":"glip.project-summary.response.v1",
        "permissions":["project:read","context:read"],
        "risk_level":"LOW",
        "governance_required":False,
        "runtime":"glip",
        "status":"BETA",
        "external_write":False,
        "fallback_policy":"FALLBACK_LOCAL",
    },
    {
        "capability_id":"glip.draft_message",
        "version":"1.0.0",
        "description":"Create governed communication drafts using project-scoped authorized context.",
        "input_schema":"glip.draft-message.request.v1",
        "output_schema":"glip.draft-message.response.v1",
        "permissions":["project:read","context:read","draft:create"],
        "risk_level":"MEDIUM",
        "governance_required":True,
        "runtime":"orkio",
        "status":"BETA",
        "external_write":False,
        "human_approval_required":True,
        "fallback_policy":"FAIL_SAFE",
    },
    {
        "capability_id":"glip.risk_scan",
        "version":"1.0.0",
        "description":"Deterministic first-pass scan for communication/domain commitment risks.",
        "input_schema":"glip.risk-scan.request.v1",
        "output_schema":"glip.risk-scan.response.v1",
        "permissions":["project:read"],
        "risk_level":"MEDIUM",
        "governance_required":True,
        "runtime":"glip",
        "status":"BETA",
        "external_write":False,
        "fallback_policy":"FAIL_CLOSED",
    },
]
